version: "3.8"

services:
  db:
    image: postgres:13
    container_name: fhtways_db
    environment:
      POSTGRES_USER: fhtways_user
      POSTGRES_PASSWORD: fhtways_pw
      POSTGRES_DB: fhtways_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
