export interface Node {
    id: number;
    name: string;
    coord_x: number;
    coord_y: number;
    display_x: number;
    display_y: number;
    type: string;
}

export const allNodes: Node[] = [
    {
        id: 1,
        name: "stairs_left",
        coord_x: 0,
        coord_y: 6,
        display_x: 100,
        display_y: 200,
        type: "stairs",
    },
    {
        id: 2,
        name: "stairs_left_conn",
        coord_x: 0,
        coord_y: 0,
        display_x: 100,
        display_y: 190,
        type: "conn",
    },
    {
        id: 3,
        name: "F4.27",
        coord_x: 2,
        coord_y: 4,
        display_x: 120,
        display_y: 240,
        type: "room",
    },
    {
        id: 4,
        name: "F4.27_c",
        coord_x: 2,
        coord_y: 0,
        display_x: 120,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 5,
        name: "F4.26",
        coord_x: 5,
        coord_y: 2,
        display_x: 150,
        display_y: 220,
        type: "room",
    },
    {
        id: 6,
        name: "F4.26_c",
        coord_x: 5,
        coord_y: 0,
        display_x: 150,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 7,
        name: "F4.25",
        coord_x: 8,
        coord_y: 2,
        display_x: 180,
        display_y: 220,
        type: "room",
    },
    {
        id: 8,
        name: "F4.25_c",
        coord_x: 8,
        coord_y: 0,
        display_x: 180,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 9,
        name: "F4.24",
        coord_x: 11,
        coord_y: 2,
        display_x: 110,
        display_y: 220,
        type: "room",
    },
    {
        id: 10,
        name: "F4.24_c",
        coord_x: 11,
        coord_y: 0,
        display_x: 110,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 11,
        name: "F4.23",
        coord_x: 14,
        coord_y: 2,
        display_x: 140,
        display_y: 220,
        type: "room",
    },
    {
        id: 12,
        name: "F4.23_c",
        coord_x: 14,
        coord_y: 0,
        display_x: 140,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 13,
        name: "F4.22",
        coord_x: 17,
        coord_y: 2,
        display_x: 170,
        display_y: 220,
        type: "room",
    },
    {
        id: 14,
        name: "F4.22_c",
        coord_x: 17,
        coord_y: 0,
        display_x: 170,
        display_y: 190,
        type: "corridor",
    },
    {
        id: 15,
        name: "F4.20",
        coord_x: 20,
        coord_y: 5,
        display_x: 200,
        display_y: 250,
        type: "room",
    },
    {
        id: 16,
        name: "F4.20_c",
        coord_x: 20,
        coord_y: 3,
        display_x: 200,
        display_y: 230,
        type: "corridor",
    },
    {
        id: 17,
        name: "F4.20_conn",
        coord_x: 20,
        coord_y: 0,
        display_x: 200,
        display_y: 190,
        type: "conn",
    },
    {
        id: 18,
        name: "door_left",
        coord_x: 21,
        coord_y: 3,
        display_x: 210,
        display_y: 230,
        type: "door",
    },
    {
        id: 19,
        name: "TOILETTE",
        coord_x: 25,
        coord_y: 1,
        display_x: 250,
        display_y: 210,
        type: "TOILETTE",
    },
    {
        id: 20,
        name: "AUFZUG",
        coord_x: 30,
        coord_y: 1,
        display_x: 300,
        display_y: 210,
        type: "AUFZUG",
    },
    {
        id: 21,
        name: "F4",
        coord_x: 100,
        coord_y: 6,
        display_x: 280,
        display_y: 260,
        type: "stairs",
    },
    {
        id: 22,
        name: "door_right",
        coord_x: 35,
        coord_y: 3,
        display_x: 350,
        display_y: 230,
        type: "door",
    },
    {
        id: 23,
        name: "F4.08",
        coord_x: 37,
        coord_y: 5,
        display_x: 370,
        display_y: 250,
        type: "room",
    },
    {
        id: 24,
        name: "F4.01",
        coord_x: 37,
        coord_y: 1,
        display_x: 370,
        display_y: 210,
        type: "room",
    },
    {
        id: 25,
        name: "F4.01_F4.08_c",
        coord_x: 37,
        coord_y: 3,
        display_x: 370,
        display_y: 230,
        type: "corridor",
    },
    {
        id: 26,
        name: "F4.07",
        coord_x: 40,
        coord_y: 5,
        display_x: 400,
        display_y: 250,
        type: "room",
    },
    {
        id: 27,
        name: "F4.02",
        coord_x: 40,
        coord_y: 1,
        display_x: 400,
        display_y: 210,
        type: "room",
    },
    {
        id: 28,
        name: "F4.02_F4.07_c",
        coord_x: 40,
        coord_y: 3,
        display_x: 400,
        display_y: 230,
        type: "corridor",
    },
    {
        id: 29,
        name: "F4.06",
        coord_x: 43,
        coord_y: 5,
        display_x: 430,
        display_y: 250,
        type: "room",
    },
    {
        id: 30,
        name: "F4.03",
        coord_x: 43,
        coord_y: 1,
        display_x: 430,
        display_y: 210,
        type: "room",
    },
    {
        id: 31,
        name: "F4.03_F4.06_c",
        coord_x: 43,
        coord_y: 3,
        display_x: 430,
        display_y: 230,
        type: "corridor",
    },
    {
        id: 32,
        name: "F4.05",
        coord_x: 46,
        coord_y: 6,
        display_x: 460,
        display_y: 260,
        type: "room",
    },
    {
        id: 33,
        name: "F4.04",
        coord_x: 46,
        coord_y: 0,
        display_x: 460,
        display_y: 200,
        type: "room",
    },
    {
        id: 34,
        name: "F4.04_F4.05_c",
        coord_x: 46,
        coord_y: 3,
        display_x: 460,
        display_y: 230,
        type: "corridor",
    },
    {
        id: 35,
        name: "stairs_right_conn",
        coord_x: 48,
        coord_y: 3,
        display_x: 480,
        display_y: 230,
        type: "conn",
    },
    {
        id: 36,
        name: "stairs_right",
        coord_x: 48,
        coord_y: 8,
        display_x: 480,
        display_y: 280,
        type: "stairs",
    },
];