name: Frontend CI/CD Pipeline

on:
    push:
        paths:
            - "frontend/**"
    pull_request:
        paths:
            - "frontend/**"

jobs:
    install-dependencies:
        name: Install Dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install npm dependencies
              run: |
                  cd frontend
                  npm ci

    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - name: Lint the code
              run: |
                  cd frontend
                  npm run lint

    sonarqube:
        name: SonarCloud Analysis
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Run SonarCloud Analysis
              uses: sonarsource/sonarqube-scan-action@v2
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: sonarqube
        steps:
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-frontend:latest frontend/.
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-frontend:latest
