name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip dependencies
        run: |
          pip install -r backend/requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run Tests
        working-directory: backend
        run: python manage.py test

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    steps:
      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-backend:latest backend/.
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-backend:latest
