name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip dependencies
        working-directory: backend
        run: pip install -r requirements.txt

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-22.04
    needs: install-dependencies
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=fhtways-fullstack
            -Dsonar.organization=fhtways
            -Dsonar.host.url=https://sonarcloud.io

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    needs: sonarqube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-backend:latest backend/.
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-backend:latest
