name: Frontend CI/CD Pipeline

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install npm dependencies
        run: |
          cd frontend
          npm ci

  lint:
    name: Lint Code
    runs-on: ubuntu-22.04
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: Lint the code
        working-directory: frontend
        run: npm run lint

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-22.04
    needs: lint
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    needs: sonarqube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-frontend:latest frontend/.
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fhtways-frontend:latest
